### PR TITLE
Added generic controls

### PR DESCRIPTION
**Pull request by fordacious**
Simultaneously fixing the issue in super frame that prevents generic controls from functioning

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks so much. Does this depend on a PR on superframe?

**Comment by fordacious** [comment]
It depends on it to work, but will simply behave as previously until the superframe components are updated.

**Comment by fordacious** [comment]
Superframe PR (here)[https://github.com/supermedium/superframe/pull/287]

**Comment by fordacious** [comment]
Should be good to go now

**Comment by fordacious** [comment]
Just tested on the site and it's looking good!

**Pull request merged**
