### PR TITLE
add Node version to build instructions

### PR DESCRIPTION
**Pull request by chrisplatorres**
There are errors when running `npm i` on Node v`12.2.0` and `12.3.0`, but `11.15` works fine.  #26 

The latest working Node version should be specified in README instructions.

### CODE REVIEW

**Comment by ngokevin** [comment]
How about https://www.npmjs.com/package/ensure-node-env?

**Comment by chrisplatorres** [comment]
That's way better, I'll update the PR.

**Comment by chrisplatorres** [comment]
Now checks for < 11.15.

**Comment by ngokevin** [comment]
Thanks for all the support so far!

**Pull request merged**
