### PR TITLE
Update Aframe to v1.3.0

### PR DESCRIPTION
**Pull request by Maxmystere**
This will fix moonrider on chrome

I took the commit from https://github.com/aframevr/aframe/releases/tag/v1.3.0

### CODE REVIEW

**Comment by zakharvoit** [comment]
Can this be merged? We use https://moonrider.xyz/ as a sample for the Wolvic browser and this PR would fix our Chromium based versions.

**Comment by Maxmystere** [comment]
You can use https://maxmystere.github.io/moonrider/ while merge is pending

**Comment by dmarcos** [comment]
Sorry for being slow at this. Thanks so much for the patience.

**Comment by dmarcos** [comment]
Thanks so much for tracking the issue down

**Comment by dmarcos** [comment]
@Maxmystere Any ideas for a quick fix of https://github.com/supermedium/moonrider/issues/186 ?

**Comment by Maxmystere** [comment]
Ho sadly I do not own a VR headset at the moment but will get back at it if I ever get my hands on one
I will at least rebase 1.4.2 and check if it's running to have a base for anyone working on it

**Comment by dmarcos** [comment]
@Maxmystere Thanks so much! If you wanna give it a try you can reproduce https://github.com/supermedium/moonrider/issues/186 without a headset and the [WebXR emulator extension](https://github.com/meta-quest/immersive-web-emulator). Steps:

1. On https://moonrider.xyz/ click begin (with mouse)
2. Click on search
3. Enter VR

When entering VR the controllers activate and the laser pointer on the initial position already hits the keyboard keys causing the following error:

```
  Cannot read properties of undefined (reading '0')
    at i.updateKeyColorPlane (build.js?v=3:1292:1182731)
    at i.tick (build.js?v=3:1292:1181486)
    at HTMLElement.value (a-scene.js:739:34)
    at HTMLElement.value (a-scene.js:789:36)
    at bind.js:12:17
    at onAnimationFrame (three.js:18890:1)
    at Object.onAnimationFrame [as callback] (three.js:9460:1)
    at XRSession$1.<computed>.onDeviceFrame (webxr-polyfill.js:3166:28)
```

**Comment by svillar** [comment]
> You can use https://maxmystere.github.io/moonrider/ while merge is pending

Note that this is also broken. It's affected by #186 as well

**Comment by dmarcos** [comment]
I've reverted this PR until we can found a solution for https://github.com/supermedium/moonrider/issues/186

I have created a branch with the state of this merge just in case someone wants to continue:

https://github.com/supermedium/moonrider/tree/moonrider1.3.0

It would be great to update to A-Frame 1.5.0 if possible.

**Pull request merged**
